spring:
  thymeleaf:
    cache: false #关闭缓存，修改后立即生效，不需要重启项目
  datasource:
    url: jdbc:mysql://localhost:3306/wjfnews?serverTimezone=GMT
    username: root
    password: weijianfeng666
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  main:
    allow-bean-definition-overriding: true
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true

mybatis:
  mapper-locations:  classpath:mapper/*.xml
ftp:
  ipPath: 47.93.234.52
  port: 21
  user: ftpuser
  password: weijianfeng666
  upLoadPath: /home/ftpuser/ftpfile

server:
  port: 8080

