spring:
  mail:
    username: 1716416169@qq.com
    password: ngrwihdkgpgvcafe
    host: smtp.qq.com #开启加密验证
    properties:
      mail:
        smtp:
          ssl:
            enable: true

  thymeleaf:
    cache: false #关闭缓存，修改后立即生效，不需要重启项目
  datasource:
    url: jdbc:mysql://localhost:3306/wjfnews?serverTimezone=GMT
    username: root
    password: weijianfeng666
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  main:
    allow-bean-definition-overriding: true
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update #如果表更改则更新
    # ddl-auto: create-drop  #启动后删除原表再创建
    show-sql: true  #开启sql语句展示

mybatis:
  mapper-locations:  classpath:mapper/*.xml
ftp:
  ipPath: 47.93.234.52
  port: 21
  user: ftpuser
  password: weijianfeng666
  upLoadPath: /home/ftpuser/ftpfile
server:
  port: 8080

